name: 2016 rust PR

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - '2016/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: "2016"
      run: cargo build --verbose
    - name: Run tests debug
      working-directory: "2016"
      run: cargo test --verbose
    - name: Run tests release
      working-directory: "2016"
      run: cargo test --verbose --release
